export const countryStateCityData = {
  India: {
    states: {
      AndhraPradesh: ["Hyderabad", "Visakhapatnam", "Vijayawada"],
      ArunachalPradesh: ["Itanagar", "Tawang", "Ziro"],
      Assam: ["Guwahati", "Dibrugarh", "Jorhat"],
      Bihar: ["Patna", "Gaya", "Bhagalpur"],
      Delhi: ["New Delhi", "Delhi"],
      Goa: ["Panaji", "Vasco da Gama", "Margao"],
      Gujarat: ["Ahmedabad", "Surat", "Vadodara"],
      Haryana: ["Chandigarh", "Faridabad", "Gurugram"],
      HimachalPradesh: ["Shimla", "Manali", "Dharamshala"],
      JammuKashmir: ["Srinagar", "Jammu", "Leh"],
      Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad"],
      Karnataka: ["Bengaluru", "Mysuru", "Hubli"],
      Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode"],
      MadhyaPradesh: ["Bhopal", "Indore", "Gwalior"],
      Maharashtra: [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Nashik",
        "SambhajiNagar",
        "Buldhana",
        "Jalgaon",
        "Malegaon",
        "Bhusawal",
      ],
      Manipur: ["Imphal", "Churachandpur", "Thoubal"],
      Meghalaya: ["Shillong", "Tura", "Jowai"],
      Mizoram: ["Aizawl", "Lunglei", "Champhai"],
      Nagaland: ["Kohima", "Dimapur", "Mokokchung"],
      Odisha: ["Bhubaneswar", "Cuttack", "Rourkela"],
      Punjab: ["Chandigarh", "Amritsar", "Ludhiana"],
      Rajasthan: ["Jaipur", "Udaipur", "Jodhpur"],
      Sikkim: ["Gangtok", "Pakyong", "Namchi"],
      TamilNadu: ["Chennai", "Coimbatore", "Madurai"],
      Telangana: ["Hyderabad", "Warangal", "Khammam"],
      Tripura: ["Agartala", "Udaipur", "Dharmanagar"],
      UttarPradesh: ["Lucknow", "Kanpur", "Varanasi"],
      Uttarakhand: ["Dehradun", "Haridwar", "Nainital"],
      WestBengal: ["Kolkata", "Howrah", "Durgapur"],
    },
  },
  USA: {
    states: {
      California: ["Los Angeles", "San Francisco", "San Diego"],
      NewYork: ["New York City", "Buffalo", "Rochester"],
      Texas: ["Houston", "Austin", "Dallas"],
      Florida: ["Miami", "Orlando", "Tampa"],
      Illinois: ["Chicago", "Naperville", "Peoria"],
      Pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown"],
    },
  },
  Canada: {
    states: {
      Ontario: ["Toronto", "Ottawa", "Hamilton"],
      Quebec: ["Montreal", "Quebec City", "Gatineau"],
      BritishColumbia: ["Vancouver", "Victoria", "Surrey"],
      Alberta: ["Calgary", "Edmonton", "Banff"],
    },
  },
  Australia: {
    states: {
      NewSouthWales: ["Sydney", "Newcastle", "Wollongong"],
      Victoria: ["Melbourne", "Geelong", "Ballarat"],
      Queensland: ["Brisbane", "Gold Coast", "Cairns"],
      WesternAustralia: ["Perth", "Mandurah", "Bunbury"],
      SouthAustralia: ["Adelaide", "Mount Gambier", "Whyalla"],
    },
  },
};
